name: Compile Latex and Release PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          work_in_root_file_dir: true
          args: -bibtex -pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: v0.1
          generate_release_notes: true
